CREATE AVAILABILITY GROUP [$(AGName)]
WITH (
    CLUSTER_TYPE = NONE
)
FOR REPLICA ON
N'$(AGNode1)' WITH
(
    ENDPOINT_URL = N'tcp://$(AGNode1):$(ListenerPort)',
    AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
    SEEDING_MODE = AUTOMATIC,
    FAILOVER_MODE = MANUAL,
    SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
),
N'$(AGNode2)' WITH
(
    ENDPOINT_URL = N'tcp://$(AGNode2):$(ListenerPort)',
    AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
    SEEDING_MODE = AUTOMATIC,
    FAILOVER_MODE = MANUAL,
    SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
);
